package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"rangoapp/database"
	"rangoapp/graph/model"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, data model.NewCompanyInput) (*model.Auth, error) {
	panic(fmt.Errorf("not implemented: CreateAccount - createAccount"))
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, phone string, code string, password string) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, phone string, password string) (*model.Auth, error) {
	panic(fmt.Errorf("not implemented: LoginUser - loginUser"))
}

// BlockUserAccount is the resolver for the blockUserAccount field.
func (r *mutationResolver) BlockUserAccount(ctx context.Context, id *string) (bool, error) {
	panic(fmt.Errorf("not implemented: BlockUserAccount - blockUserAccount"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, data model.UpdateUserInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// UpdateCompany is the resolver for the updateCompany field.
func (r *mutationResolver) UpdateCompany(ctx context.Context, id string, data *model.UpdateCompanyInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateCompany - updateCompany"))
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, data model.NewProductInput) (bool, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, data model.UpdateProductInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, phone string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Companies is the resolver for the companies field.
func (r *queryResolver) Companies(ctx context.Context) ([]*model.Company, error) {
	panic(fmt.Errorf("not implemented: Companies - companies"))
}

// Company is the resolver for the company field.
func (r *queryResolver) Company(ctx context.Context, id *string, name *string, code *string) (*model.Company, error) {
	panic(fmt.Errorf("not implemented: Company - company"))
}

// Sales is the resolver for the sales field.
func (r *queryResolver) Sales(ctx context.Context) ([]*model.Sale, error) {
	panic(fmt.Errorf("not implemented: Sales - sales"))
}

// Sale is the resolver for the sale field.
func (r *queryResolver) Sale(ctx context.Context, id *string) (*model.Sale, error) {
	panic(fmt.Errorf("not implemented: Sale - sale"))
}

// Approvisionements is the resolver for the approvisionements field.
func (r *queryResolver) Approvisionements(ctx context.Context) ([]*model.Approvisionement, error) {
	panic(fmt.Errorf("not implemented: Approvisionements - approvisionements"))
}

// MouvementStock is the resolver for the mouvementStock field.
func (r *queryResolver) MouvementStock(ctx context.Context) ([]*model.MouvementStock, error) {
	panic(fmt.Errorf("not implemented: MouvementStock - mouvementStock"))
}

// Stock is the resolver for the stock field.
func (r *queryResolver) Stock(ctx context.Context) ([]*model.Stock, error) {
	panic(fmt.Errorf("not implemented: Stock - stock"))
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// Caisse is the resolver for the caisse field.
func (r *queryResolver) Caisse(ctx context.Context) (*model.Caisse, error) {
	panic(fmt.Errorf("not implemented: Caisse - caisse"))
}

// CaisseTrans is the resolver for the caisseTrans field.
func (r *queryResolver) CaisseTrans(ctx context.Context) ([]*model.Trans, error) {
	panic(fmt.Errorf("not implemented: CaisseTrans - caisseTrans"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var (
	db = database.ConnectDB()
)
