// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AddInventoryItemInput struct {
	InventoryID      string  `json:"inventoryId"`
	ProductID        string  `json:"productId"`
	PhysicalQuantity float64 `json:"physicalQuantity"`
	Reason           *string `json:"reason,omitempty"`
}

type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type Caisse struct {
	CurrentBalance float64 `json:"currentBalance"`
	In             float64 `json:"in"`
	Out            float64 `json:"out"`
	TotalBenefice  float64 `json:"totalBenefice"`
	Currency       string  `json:"currency"`
	StoreID        *string `json:"storeId,omitempty"`
	Store          *Store  `json:"store,omitempty"`
}

type CaisseRapport struct {
	StoreID            *string              `json:"storeId,omitempty"`
	Store              *Store               `json:"store,omitempty"`
	Currency           string               `json:"currency"`
	Period             string               `json:"period"`
	StartDate          string               `json:"startDate"`
	EndDate            string               `json:"endDate"`
	TotalEntrees       float64              `json:"totalEntrees"`
	TotalSorties       float64              `json:"totalSorties"`
	TotalBenefice      float64              `json:"totalBenefice"`
	SoldeInitial       float64              `json:"soldeInitial"`
	SoldeFinal         float64              `json:"soldeFinal"`
	NombreTransactions int                  `json:"nombreTransactions"`
	Transactions       []*CaisseTransaction `json:"transactions"`
	ResumeParJour      []*CaisseResumeJour  `json:"resumeParJour,omitempty"`
}

type CaisseResumeJour struct {
	Date               string  `json:"date"`
	Entrees            float64 `json:"entrees"`
	Sorties            float64 `json:"sorties"`
	Benefice           float64 `json:"benefice"`
	Solde              float64 `json:"solde"`
	NombreTransactions int     `json:"nombreTransactions"`
}

type CaisseTransaction struct {
	ID          string  `json:"id"`
	Amount      float64 `json:"amount"`
	Operation   string  `json:"operation"`
	Description string  `json:"description"`
	Currency    string  `json:"currency"`
	StoreID     string  `json:"storeId"`
	Store       *Store  `json:"store"`
	Date        string  `json:"date"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type Client struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Phone           string  `json:"phone"`
	StoreID         string  `json:"storeId"`
	Store           *Store  `json:"store"`
	CreditLimit     float64 `json:"creditLimit"`
	CurrentDebt     float64 `json:"currentDebt"`
	AvailableCredit float64 `json:"availableCredit"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type Company struct {
	ID            string               `json:"id"`
	Name          string               `json:"name"`
	Address       string               `json:"address"`
	Phone         string               `json:"phone"`
	Email         *string              `json:"email,omitempty"`
	Description   string               `json:"description"`
	Type          string               `json:"type"`
	Logo          *string              `json:"logo,omitempty"`
	Rccm          *string              `json:"rccm,omitempty"`
	IDNat         *string              `json:"idNat,omitempty"`
	IDCommerce    *string  `json:"idCommerce,omitempty"`
	LicenseID     *string  `json:"licenseId,omitempty"`
	Stores        []*Store             `json:"stores"`
	Subscription  *CompanySubscription `json:"subscription"`
	ExchangeRates []*ExchangeRate      `json:"exchangeRates"`
	CreatedAt     string               `json:"createdAt"`
	UpdatedAt     string               `json:"updatedAt"`
}

type CompanySubscription struct {
	ID                    string  `json:"id"`
	CompanyID             string  `json:"companyId"`
	Plan                  string  `json:"plan"`
	Status                string  `json:"status"`
	TrialStartDate        string  `json:"trialStartDate"`
	TrialEndDate          string  `json:"trialEndDate"`
	SubscriptionStartDate *string `json:"subscriptionStartDate,omitempty"`
	SubscriptionEndDate   *string `json:"subscriptionEndDate,omitempty"`
	PaymentMethod         *string `json:"paymentMethod,omitempty"`
	PaymentID             *string `json:"paymentId,omitempty"`
	MaxStores             int     `json:"maxStores"`
	MaxUsers              int     `json:"maxUsers"`
	DaysRemaining         int     `json:"daysRemaining"`
	IsTrialExpired        bool    `json:"isTrialExpired"`
	CreatedAt             string  `json:"createdAt"`
	UpdatedAt             string  `json:"updatedAt"`
}

type CreateCaisseTransactionInput struct {
	Amount      float64 `json:"amount"`
	Operation   string  `json:"operation"`
	Description string  `json:"description"`
	Currency    *string `json:"currency,omitempty"`
	StoreID     string  `json:"storeId"`
	Date        *string `json:"date,omitempty"`
}

type CreateClientInput struct {
	Name        string   `json:"name"`
	Phone       string   `json:"phone"`
	StoreID     string   `json:"storeId"`
	CreditLimit *float64 `json:"creditLimit,omitempty"`
}

type CreateCompanyInput struct {
	Name        string  `json:"name"`
	Address     string  `json:"address"`
	Phone       string  `json:"phone"`
	Email       *string `json:"email,omitempty"`
	Description string  `json:"description"`
	Type        string  `json:"type"`
	Logo        *string `json:"logo,omitempty"`
	Rccm        *string `json:"rccm,omitempty"`
	IDNat       *string `json:"idNat,omitempty"`
	IDCommerce  *string `json:"idCommerce,omitempty"`
}

type CreateFactureInput struct {
	Products []*FactureProductInput `json:"products"`
	ClientID string                 `json:"clientId"`
	StoreID  string                 `json:"storeId"`
	Quantity int                    `json:"quantity"`
	Price    float64                `json:"price"`
	Currency *string                `json:"currency,omitempty"`
	Date     string                 `json:"date"`
}

type CreateInventoryInput struct {
	StoreID     string `json:"storeId"`
	Description string `json:"description"`
}

type CreateProductInput struct {
	Name    string `json:"name"`
	Mark    string `json:"mark"`
	StoreID string `json:"storeId"`
}

type CreateProviderInput struct {
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Address string `json:"address"`
	StoreID string `json:"storeId"`
}

type CreateRapportStoreInput struct {
	ProductID string  `json:"productId"`
	StoreID   string  `json:"storeId"`
	Quantity  float64 `json:"quantity"`
	Type      string  `json:"type"`
	Date      string  `json:"date"`
}

type CreateSaleInput struct {
	Basket      []*SaleProductInput `json:"basket"`
	PriceToPay  float64             `json:"priceToPay"`
	PricePayed  float64             `json:"pricePayed"`
	ClientID    *string             `json:"clientId,omitempty"`
	StoreID     string              `json:"storeId"`
	Currency    *string             `json:"currency,omitempty"`
	PaymentType *string             `json:"paymentType,omitempty"`
	Date        *string             `json:"date,omitempty"`
}

type CreateStoreInput struct {
	Name                string   `json:"name"`
	Address             string   `json:"address"`
	Phone               string   `json:"phone"`
	DefaultCurrency     *string  `json:"defaultCurrency,omitempty"`
	SupportedCurrencies []string `json:"supportedCurrencies,omitempty"`
}

type CreateUserInput struct {
	Name     string  `json:"name"`
	Phone    string  `json:"phone"`
	Password string  `json:"password"`
	Role     string  `json:"role"`
	StoreID  *string `json:"storeId,omitempty"`
}

type Debt struct {
	ID          string         `json:"id"`
	SaleID      string         `json:"saleId"`
	Sale        *Sale          `json:"sale"`
	ClientID    string         `json:"clientId"`
	Client      *Client        `json:"client"`
	StoreID     string         `json:"storeId"`
	Store       *Store         `json:"store"`
	TotalAmount float64        `json:"totalAmount"`
	AmountPaid  float64        `json:"amountPaid"`
	AmountDue   float64        `json:"amountDue"`
	Currency    string         `json:"currency"`
	Status      string         `json:"status"`
	PaymentType string         `json:"paymentType"`
	Payments    []*DebtPayment `json:"payments"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
	PaidAt      *string        `json:"paidAt,omitempty"`
}

type DebtPayment struct {
	ID          string  `json:"id"`
	DebtID      string  `json:"debtId"`
	Debt        *Debt   `json:"debt"`
	Amount      float64 `json:"amount"`
	Currency    string  `json:"currency"`
	OperatorID  string  `json:"operatorId"`
	Operator    *User   `json:"operator"`
	StoreID     string  `json:"storeId"`
	Store       *Store  `json:"store"`
	Description string  `json:"description"`
	CreatedAt   string  `json:"createdAt"`
}

type ExchangeRate struct {
	FromCurrency string  `json:"fromCurrency"`
	ToCurrency   string  `json:"toCurrency"`
	Rate         float64 `json:"rate"`
	IsDefault    bool    `json:"isDefault"`
	UpdatedAt    string  `json:"updatedAt"`
	UpdatedBy    string  `json:"updatedBy"`
}

type ExchangeRateInput struct {
	FromCurrency string  `json:"fromCurrency"`
	ToCurrency   string  `json:"toCurrency"`
	Rate         float64 `json:"rate"`
}

type Facture struct {
	ID            string            `json:"id"`
	FactureNumber string            `json:"factureNumber"`
	Products      []*FactureProduct `json:"products"`
	Quantity      int               `json:"quantity"`
	Date          string            `json:"date"`
	Price         float64           `json:"price"`
	Currency      string            `json:"currency"`
	Client        *Client           `json:"client"`
	StoreID       string            `json:"storeId"`
	Store         *Store            `json:"store"`
	CreatedAt     string            `json:"createdAt"`
	UpdatedAt     string            `json:"updatedAt"`
}

type FactureProduct struct {
	ProductID string   `json:"productId"`
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	Price     float64  `json:"price"`
}

type FactureProductInput struct {
	ProductID string  `json:"productId"`
	Quantity  int     `json:"quantity"`
	Price     float64 `json:"price"`
}

type Inventory struct {
	ID          string           `json:"id"`
	StoreID     string           `json:"storeId"`
	Store       *Store           `json:"store"`
	OperatorID  string           `json:"operatorId"`
	Operator    *User            `json:"operator"`
	Status      string           `json:"status"`
	StartDate   string           `json:"startDate"`
	EndDate     *string          `json:"endDate,omitempty"`
	Description string           `json:"description"`
	Items       []*InventoryItem `json:"items"`
	TotalItems  int              `json:"totalItems"`
	TotalValue  float64          `json:"totalValue"`
	CreatedAt   string           `json:"createdAt"`
	UpdatedAt   string           `json:"updatedAt"`
}

type InventoryItem struct {
	ProductID        string   `json:"productId"`
	Product          *Product `json:"product"`
	ProductName      string   `json:"productName"`
	SystemQuantity   float64  `json:"systemQuantity"`
	PhysicalQuantity float64  `json:"physicalQuantity"`
	Difference       float64  `json:"difference"`
	UnitPrice        float64  `json:"unitPrice"`
	TotalValue       float64  `json:"totalValue"`
	Reason           *string  `json:"reason,omitempty"`
	CountedBy        string   `json:"countedBy"`
	CountedByUser    *User    `json:"countedByUser"`
	CountedAt        string   `json:"countedAt"`
}

type Mutation struct {
}

type Product struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Mark      string `json:"mark"`
	StoreID   string `json:"storeId"`
	Store     *Store `json:"store"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ProductInStock struct {
	ID         string    `json:"id"`
	ProductID  string    `json:"productId"`
	Product    *Product  `json:"product"`
	PriceVente float64   `json:"priceVente"`
	PriceAchat float64   `json:"priceAchat"`
	Currency   string    `json:"currency"`
	Stock      float64   `json:"stock"`
	StoreID    string    `json:"storeId"`
	Store      *Store    `json:"store"`
	ProviderID string    `json:"providerId"`
	Provider   *Provider `json:"provider"`
	CreatedAt  string    `json:"createdAt"`
	UpdatedAt  string    `json:"updatedAt"`
}

type ProductMovementStats struct {
	Product          *Product `json:"product"`
	TotalEntrees     float64  `json:"totalEntrees"`
	TotalSorties     float64  `json:"totalSorties"`
	NombreMouvements int      `json:"nombreMouvements"`
}

type Provider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Address   string `json:"address"`
	StoreID   string `json:"storeId"`
	Store     *Store `json:"store"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ProviderDebt struct {
	ID          string                 `json:"id"`
	SupplyID    string                 `json:"supplyId"`
	Supply      *StockSupply           `json:"supply"`
	ProviderID  string                 `json:"providerId"`
	Provider    *Provider              `json:"provider"`
	StoreID     string                 `json:"storeId"`
	Store       *Store                 `json:"store"`
	TotalAmount float64                `json:"totalAmount"`
	AmountPaid  float64                `json:"amountPaid"`
	AmountDue   float64                `json:"amountDue"`
	Currency    string                 `json:"currency"`
	Status      string                 `json:"status"`
	Payments    []*ProviderDebtPayment `json:"payments"`
	CreatedAt   string                 `json:"createdAt"`
	UpdatedAt   string                 `json:"updatedAt"`
	PaidAt      *string                `json:"paidAt,omitempty"`
}

type ProviderDebtPayment struct {
	ID             string        `json:"id"`
	ProviderDebtID string        `json:"providerDebtId"`
	ProviderDebt   *ProviderDebt `json:"providerDebt"`
	Amount         float64       `json:"amount"`
	Currency       string        `json:"currency"`
	OperatorID     string        `json:"operatorId"`
	Operator       *User         `json:"operator"`
	StoreID        string        `json:"storeId"`
	Store          *Store        `json:"store"`
	Description    string        `json:"description"`
	CreatedAt      string        `json:"createdAt"`
}

type Query struct {
}

type RapportStore struct {
	ID        string   `json:"id"`
	Type      string   `json:"type"`
	Product   *Product `json:"product"`
	Quantity  float64  `json:"quantity"`
	Date      string   `json:"date"`
	StoreID   string   `json:"storeId"`
	Store     *Store   `json:"store"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type Sale struct {
	ID          string         `json:"id"`
	Basket      []*SaleProduct `json:"basket"`
	PriceToPay  float64        `json:"priceToPay"`
	PricePayed  float64        `json:"pricePayed"`
	Change      float64        `json:"change"`
	Benefice    float64        `json:"benefice"`
	Currency    string         `json:"currency"`
	Client      *Client        `json:"client,omitempty"`
	Operator    *User          `json:"operator"`
	StoreID     string         `json:"storeId"`
	Store       *Store         `json:"store"`
	PaymentType string         `json:"paymentType"`
	AmountDue   float64        `json:"amountDue"`
	DebtStatus  string         `json:"debtStatus"`
	DebtID      *string        `json:"debtId,omitempty"`
	Debt        *Debt          `json:"debt,omitempty"`
	Date        string         `json:"date"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type SaleList struct {
	ID          string  `json:"id"`
	Date        string  `json:"date"`
	CreatedAt   string  `json:"createdAt"`
	PriceToPay  float64 `json:"priceToPay"`
	PricePayed  float64 `json:"pricePayed"`
	Change      float64 `json:"change"`
	Currency    string  `json:"currency"`
	Client      *Client `json:"client,omitempty"`
	BasketCount int     `json:"basketCount"`
	TotalItems  float64 `json:"totalItems"`
	StoreID     string  `json:"storeId"`
	PaymentType string  `json:"paymentType"`
	AmountDue   float64 `json:"amountDue"`
	DebtStatus  string  `json:"debtStatus"`
}

type SaleProduct struct {
	ProductInStockID string          `json:"productInStockId"`
	ProductInStock   *ProductInStock `json:"productInStock"`
	Quantity         float64         `json:"quantity"`
	Price            float64         `json:"price"`
}

type SaleProductInput struct {
	ProductInStockID string  `json:"productInStockId"`
	Quantity         float64 `json:"quantity"`
	Price            float64 `json:"price"`
}

type SalesStats struct {
	TotalSales    int     `json:"totalSales"`
	TotalRevenue  float64 `json:"totalRevenue"`
	TotalItems    float64 `json:"totalItems"`
	AverageSale   float64 `json:"averageSale"`
	TotalBenefice float64 `json:"totalBenefice"`
}

type StockMovement struct {
	ID            string            `json:"id"`
	ProductID     string            `json:"productId"`
	Product       *Product          `json:"product"`
	StoreID       string            `json:"storeId"`
	Store         *Store            `json:"store"`
	Type          StockMovementType `json:"type"`
	Quantity      float64           `json:"quantity"`
	UnitPrice     float64           `json:"unitPrice"`
	TotalValue    float64           `json:"totalValue"`
	Currency      string            `json:"currency"`
	Reason        *string           `json:"reason,omitempty"`
	Reference     *string           `json:"reference,omitempty"`
	ReferenceType *string           `json:"referenceType,omitempty"`
	ReferenceID   *string           `json:"referenceId,omitempty"`
	OperatorID    string            `json:"operatorId"`
	Operator      *User             `json:"operator"`
	CreatedAt     string            `json:"createdAt"`
	UpdatedAt     string            `json:"updatedAt"`
}

type StockMovementByProduct struct {
	ProductID           string   `json:"productId"`
	Product             *Product `json:"product"`
	TotalEntrees        float64  `json:"totalEntrees"`
	TotalSorties        float64  `json:"totalSorties"`
	TotalAjustements    float64  `json:"totalAjustements"`
	SoldeInitial        float64  `json:"soldeInitial"`
	SoldeFinal          float64  `json:"soldeFinal"`
	NombreMouvements    int      `json:"nombreMouvements"`
	ValeurTotaleEntrees float64  `json:"valeurTotaleEntrees"`
	ValeurTotaleSorties float64  `json:"valeurTotaleSorties"`
}

type StockReport struct {
	StoreID              string                    `json:"storeId"`
	Store                *Store                    `json:"store"`
	Currency             string                    `json:"currency"`
	Period               string                    `json:"period"`
	StartDate            string                    `json:"startDate"`
	EndDate              string                    `json:"endDate"`
	TotalEntrees         float64                   `json:"totalEntrees"`
	TotalSorties         float64                   `json:"totalSorties"`
	TotalAjustements     float64                   `json:"totalAjustements"`
	SoldeInitial         float64                   `json:"soldeInitial"`
	SoldeFinal           float64                   `json:"soldeFinal"`
	NombreMouvements     int                       `json:"nombreMouvements"`
	MouvementsParProduit []*StockMovementByProduct `json:"mouvementsParProduit"`
	ResumeParJour        []*StockReportResumeJour  `json:"resumeParJour"`
	Mouvements           []*StockMovement          `json:"mouvements"`
}

type StockReportResumeJour struct {
	Date                string  `json:"date"`
	Entrees             float64 `json:"entrees"`
	Sorties             float64 `json:"sorties"`
	Ajustements         float64 `json:"ajustements"`
	Solde               float64 `json:"solde"`
	NombreMouvements    int     `json:"nombreMouvements"`
	ValeurTotaleEntrees float64 `json:"valeurTotaleEntrees"`
	ValeurTotaleSorties float64 `json:"valeurTotaleSorties"`
}

type StockStats struct {
	TotalProducts          int                     `json:"totalProducts"`
	TotalValue             float64                 `json:"totalValue"`
	ProductsLowStock       int                     `json:"productsLowStock"`
	ProductsOutOfStock     int                     `json:"productsOutOfStock"`
	TotalEntrees           float64                 `json:"totalEntrees"`
	TotalSorties           float64                 `json:"totalSorties"`
	TopProductsByMovements []*ProductMovementStats `json:"topProductsByMovements"`
}

type StockSupply struct {
	ID               string          `json:"id"`
	ProductID        string          `json:"productId"`
	Product          *Product        `json:"product"`
	ProductInStockID string          `json:"productInStockId"`
	ProductInStock   *ProductInStock `json:"productInStock"`
	Quantity         float64         `json:"quantity"`
	PriceAchat       float64         `json:"priceAchat"`
	PriceVente       float64         `json:"priceVente"`
	Currency         string          `json:"currency"`
	ProviderID       string          `json:"providerId"`
	Provider         *Provider       `json:"provider"`
	StoreID          string          `json:"storeId"`
	Store            *Store          `json:"store"`
	OperatorID       string          `json:"operatorId"`
	Operator         *User           `json:"operator"`
	PaymentType      string          `json:"paymentType"`
	ProviderDebtID   *string         `json:"providerDebtId,omitempty"`
	ProviderDebt     *ProviderDebt   `json:"providerDebt,omitempty"`
	Date             string          `json:"date"`
	CreatedAt        string          `json:"createdAt"`
	UpdatedAt        string          `json:"updatedAt"`
}

type StockSupplyInput struct {
	ProductID   string   `json:"productId"`
	Quantity    float64  `json:"quantity"`
	PriceAchat  float64  `json:"priceAchat"`
	PriceVente  float64  `json:"priceVente"`
	Currency    *string  `json:"currency,omitempty"`
	StoreID     string   `json:"storeId"`
	ProviderID  string   `json:"providerId"`
	PaymentType string   `json:"paymentType"`
	AmountPaid  *float64 `json:"amountPaid,omitempty"`
	Date        *string  `json:"date,omitempty"`
}

type Store struct {
	ID                  string   `json:"id"`
	Name                string   `json:"name"`
	Address             string   `json:"address"`
	Phone               string   `json:"phone"`
	CompanyID           string   `json:"companyId"`
	Company             *Company `json:"company"`
	DefaultCurrency     string   `json:"defaultCurrency"`
	SupportedCurrencies []string `json:"supportedCurrencies"`
	CreatedAt           string   `json:"createdAt"`
	UpdatedAt           string   `json:"updatedAt"`
}

type SubscriptionPlan struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Price         float64  `json:"price"`
	Currency      string   `json:"currency"`
	BillingPeriod string   `json:"billingPeriod"`
	Description   string   `json:"description"`
	Features      []string `json:"features"`
	MaxStores     *int     `json:"maxStores,omitempty"`
	MaxUsers      *int     `json:"maxUsers,omitempty"`
	IsActive      bool     `json:"isActive"`
	CreatedAt     string   `json:"createdAt"`
	UpdatedAt     string   `json:"updatedAt"`
}

type SubscriptionStatus struct {
	IsValid      bool                 `json:"isValid"`
	Message      *string              `json:"message,omitempty"`
	Subscription *CompanySubscription `json:"subscription,omitempty"`
	HasLicense   bool                 `json:"hasLicense"`
}

type UpdateClientInput struct {
	Name        *string  `json:"name,omitempty"`
	Phone       *string  `json:"phone,omitempty"`
	CreditLimit *float64 `json:"creditLimit,omitempty"`
}

type UpdateCompanyInput struct {
	Name        *string `json:"name,omitempty"`
	Address     *string `json:"address,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Email       *string `json:"email,omitempty"`
	Description *string `json:"description,omitempty"`
	Type        *string `json:"type,omitempty"`
	Logo        *string `json:"logo,omitempty"`
	Rccm        *string `json:"rccm,omitempty"`
	IDNat       *string `json:"idNat,omitempty"`
	IDCommerce  *string `json:"idCommerce,omitempty"`
	LicenseID   *string `json:"licenseId,omitempty"`
}

type UpdateFactureInput struct {
	Products []*FactureProductInput `json:"products,omitempty"`
	ClientID *string                `json:"clientId,omitempty"`
	Quantity *int                   `json:"quantity,omitempty"`
	Price    *float64               `json:"price,omitempty"`
	Currency *string                `json:"currency,omitempty"`
	Date     *string                `json:"date,omitempty"`
}

type UpdateProductInput struct {
	Name *string `json:"name,omitempty"`
	Mark *string `json:"mark,omitempty"`
}

type UpdateProviderInput struct {
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
}

type UpdateStoreInput struct {
	Name                *string  `json:"name,omitempty"`
	Address             *string  `json:"address,omitempty"`
	Phone               *string  `json:"phone,omitempty"`
	DefaultCurrency     *string  `json:"defaultCurrency,omitempty"`
	SupportedCurrencies []string `json:"supportedCurrencies,omitempty"`
}

type UpdateUserInput struct {
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Role    *string `json:"role,omitempty"`
	StoreID *string `json:"storeId,omitempty"`
}

type User struct {
	ID              string   `json:"id"`
	UID             string   `json:"uid"`
	Name            string   `json:"name"`
	Phone           string   `json:"phone"`
	Role            string   `json:"role"`
	IsBlocked       bool     `json:"isBlocked"`
	CompanyID       string   `json:"companyId"`
	StoreIds        []string `json:"storeIds"`
	AssignedStoreID *string  `json:"assignedStoreId,omitempty"`
	CreatedAt       string   `json:"createdAt"`
	UpdatedAt       string   `json:"updatedAt"`
}

type StockMovementType string

const (
	StockMovementTypeEntree     StockMovementType = "ENTREE"
	StockMovementTypeSortie     StockMovementType = "SORTIE"
	StockMovementTypeAjustement StockMovementType = "AJUSTEMENT"
)

var AllStockMovementType = []StockMovementType{
	StockMovementTypeEntree,
	StockMovementTypeSortie,
	StockMovementTypeAjustement,
}

func (e StockMovementType) IsValid() bool {
	switch e {
	case StockMovementTypeEntree, StockMovementTypeSortie, StockMovementTypeAjustement:
		return true
	}
	return false
}

func (e StockMovementType) String() string {
	return string(e)
}

func (e *StockMovementType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StockMovementType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StockMovementType", str)
	}
	return nil
}

func (e StockMovementType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
