// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Address struct {
	City   string `json:"city"`
	Street string `json:"street"`
}

type AddressInput struct {
	City   string `json:"city"`
	Street string `json:"street"`
}

type Approvisionement struct {
	ID       string       `json:"id"`
	Product  *Product     `json:"product"`
	Quantity float64      `json:"quantity"`
	Charges  float64      `json:"charges"`
	From     *Fournisseur `json:"from"`
	Date     string       `json:"date"`
}

type Auth struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

type Caisse struct {
	ID  string  `json:"id"`
	In  float64 `json:"in"`
	Out float64 `json:"out"`
}

type Client struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Phone *string `json:"phone,omitempty"`
	Note  *string `json:"note,omitempty"`
}

type ClientInput struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
	Note  string `json:"note"`
}

type Company struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Owner   *User   `json:"owner,omitempty"`
	Address string  `json:"address"`
	Type    string  `json:"type"`
	Logo    *string `json:"logo,omitempty"`
	IDNat   *string `json:"idNat,omitempty"`
	Detail  *string `json:"detail,omitempty"`
	Email   *string `json:"email,omitempty"`
	IsPayed bool    `json:"isPayed"`
}

type Fournisseur struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
	City  string `json:"city"`
}

type LoginData struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type MouvementStock struct {
	ID        *string       `json:"id,omitempty"`
	Product   *Product      `json:"product"`
	Quantity  float64       `json:"quantity"`
	Operation OperationEnum `json:"operation"`
	Date      string        `json:"date"`
}

type Mutation struct {
}

type NewClientInput struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
	Note  string `json:"note"`
}

type NewCompany struct {
	Name     string            `json:"name"`
	Category string            `json:"category"`
	City     string            `json:"city"`
	Address  string            `json:"address"`
	Contacts []string          `json:"contacts"`
	StateIds *NewStateIdentity `json:"stateIds"`
	Logo     string            `json:"logo"`
}

type NewCompanyInput struct {
	Name    string        `json:"name"`
	Address string        `json:"address"`
	Owner   *NewUserInput `json:"owner"`
	Type    string        `json:"type"`
	Logo    *string       `json:"logo,omitempty"`
	IDNat   *string       `json:"idNat,omitempty"`
	Detail  *string       `json:"detail,omitempty"`
	Email   *string       `json:"email,omitempty"`
}

type NewFournisseurInput struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
	City  string `json:"city"`
}

type NewProductInput struct {
	Name     string  `json:"name"`
	ImageURL *string `json:"imageUrl,omitempty"`
	PriceIn  float64 `json:"priceIn"`
	PriceOut float64 `json:"priceOut"`
	Discount float64 `json:"discount"`
	StockMin float64 `json:"stockMin"`
	Stock    float64 `json:"stock"`
	Category *string `json:"category,omitempty"`
	Unite    *string `json:"unite,omitempty"`
}

type NewSaleInput struct {
	Basket     []*ProductInBasketInput `json:"basket"`
	PricePayed float64                 `json:"pricePayed"`
	PriceToPay float64                 `json:"priceToPay"`
	Client     *ClientInput            `json:"client,omitempty"`
}

type NewStateIdentity struct {
	Rccm       *string `json:"rccm,omitempty"`
	IDNat      *string `json:"idNat,omitempty"`
	IDCommerce *string `json:"idCommerce,omitempty"`
}

type NewUserInput struct {
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	Address  string `json:"address"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type PriceProductEvolution struct {
	ID      string   `json:"id"`
	Product *Product `json:"product"`
	Price   float64  `json:"price"`
	Date    string   `json:"date"`
}

type PriceProductEvolutionInput struct {
	Product  string  `json:"product"`
	Price    float64 `json:"price"`
	Discount float64 `json:"discount"`
	Date     string  `json:"date"`
}

type Product struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	ImageURL *string  `json:"imageUrl,omitempty"`
	PriceIn  float64  `json:"priceIn"`
	Discount *float64 `json:"discount,omitempty"`
	PriceOut float64  `json:"priceOut"`
	Category *string  `json:"category,omitempty"`
	Unite    *string  `json:"unite,omitempty"`
}

type ProductInBasket struct {
	Product *Product `json:"product"`
	Count   float64  `json:"count"`
}

type ProductInBasketInput struct {
	Product *ProductInput `json:"product"`
	Count   float64       `json:"count"`
}

type ProductInput struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	ImageURL *string `json:"imageUrl,omitempty"`
	PriceIn  float64 `json:"priceIn"`
	PriceOut float64 `json:"priceOut"`
	Category *string `json:"category,omitempty"`
	Unite    *string `json:"unite,omitempty"`
}

type Query struct {
}

type Sale struct {
	ID         string             `json:"id"`
	Basket     []*ProductInBasket `json:"basket"`
	PriceToPay float64            `json:"priceToPay"`
	PricePayed float64            `json:"pricePayed"`
	Client     *Client            `json:"client"`
	Operator   *User              `json:"operator,omitempty"`
	Date       string             `json:"date"`
}

type Stock struct {
	ID       *string  `json:"id,omitempty"`
	Product  *Product `json:"product"`
	Quantity float64  `json:"quantity"`
	StockMin float64  `json:"stockMin"`
	Date     float64  `json:"date"`
}

type Trans struct {
	ID        string        `json:"id"`
	Amount    *float64      `json:"amount,omitempty"`
	Operation OperationEnum `json:"operation"`
	Date      string        `json:"date"`
}

type UpdateClientInput struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Note  *string `json:"note,omitempty"`
}

type UpdateCompanyInput struct {
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
	Type    *string `json:"type,omitempty"`
	Logo    *string `json:"logo,omitempty"`
	IDNat   *string `json:"idNat,omitempty"`
	Detail  *string `json:"detail,omitempty"`
	Email   *string `json:"email,omitempty"`
}

type UpdateFournisseurInput struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
	City  *string `json:"city,omitempty"`
}

type UpdateProductInput struct {
	Name     *string  `json:"name,omitempty"`
	ImageURL *string  `json:"imageUrl,omitempty"`
	PriceIn  *float64 `json:"priceIn,omitempty"`
	PriceOut *float64 `json:"priceOut,omitempty"`
	Discount *float64 `json:"discount,omitempty"`
	Category *string  `json:"category,omitempty"`
	Unite    *string  `json:"unite,omitempty"`
}

type UpdateUserInput struct {
	Name    *string `json:"name,omitempty"`
	Avatar  *string `json:"avatar,omitempty"`
	Address *string `json:"address,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Avatar    string  `json:"avatar"`
	Company   *string `json:"company,omitempty"`
	Address   string  `json:"address"`
	Phone     string  `json:"phone"`
	IsBlocked bool    `json:"isBlocked"`
	Password  string  `json:"password"`
	LastLogin string  `json:"lastLogin"`
}

type OperationEnum string

const (
	OperationEnumEntree OperationEnum = "Entree"
	OperationEnumSortie OperationEnum = "Sortie"
)

var AllOperationEnum = []OperationEnum{
	OperationEnumEntree,
	OperationEnumSortie,
}

func (e OperationEnum) IsValid() bool {
	switch e {
	case OperationEnumEntree, OperationEnumSortie:
		return true
	}
	return false
}

func (e OperationEnum) String() string {
	return string(e)
}

func (e *OperationEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OperationEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OperationEnum", str)
	}
	return nil
}

func (e OperationEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
