// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Client struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	StoreID   string `json:"storeId"`
	Store     *Store `json:"store"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Company struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Address     string   `json:"address"`
	Phone       string   `json:"phone"`
	Email       *string  `json:"email,omitempty"`
	Description string   `json:"description"`
	Type        string   `json:"type"`
	Logo        *string  `json:"logo,omitempty"`
	Rccm        *string  `json:"rccm,omitempty"`
	IDNat       *string  `json:"idNat,omitempty"`
	IDCommerce  *string  `json:"idCommerce,omitempty"`
	Stores      []*Store `json:"stores"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

type CreateClientInput struct {
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	StoreID string `json:"storeId"`
}

type CreateFactureInput struct {
	Products []*FactureProductInput `json:"products"`
	ClientID string                 `json:"clientId"`
	StoreID  string                 `json:"storeId"`
	Quantity int                    `json:"quantity"`
	Price    float64                `json:"price"`
	Currency string                 `json:"currency"`
	Date     string                 `json:"date"`
}

type CreateProductInput struct {
	Name       string  `json:"name"`
	Mark       string  `json:"mark"`
	PriceVente float64 `json:"priceVente"`
	PriceAchat float64 `json:"priceAchat"`
	Stock      float64 `json:"stock"`
	StoreID    string  `json:"storeId"`
}

type CreateProviderInput struct {
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Address string `json:"address"`
	StoreID string `json:"storeId"`
}

type CreateRapportStoreInput struct {
	ProductID string  `json:"productId"`
	StoreID   string  `json:"storeId"`
	Quantity  float64 `json:"quantity"`
	Type      string  `json:"type"`
	Date      string  `json:"date"`
}

type CreateStoreInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Phone   string `json:"phone"`
}

type CreateUserInput struct {
	Name     string  `json:"name"`
	Phone    string  `json:"phone"`
	Email    *string `json:"email,omitempty"`
	Password string  `json:"password"`
	Role     string  `json:"role"`
	StoreID  *string `json:"storeId,omitempty"`
}

type Facture struct {
	ID            string            `json:"id"`
	FactureNumber string            `json:"factureNumber"`
	Products      []*FactureProduct `json:"products"`
	Quantity      int               `json:"quantity"`
	Date          string            `json:"date"`
	Price         float64           `json:"price"`
	Currency      string            `json:"currency"`
	Client        *Client           `json:"client"`
	StoreID       string            `json:"storeId"`
	Store         *Store            `json:"store"`
	CreatedAt     string            `json:"createdAt"`
	UpdatedAt     string            `json:"updatedAt"`
}

type FactureProduct struct {
	ProductID string   `json:"productId"`
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	Price     float64  `json:"price"`
}

type FactureProductInput struct {
	ProductID string  `json:"productId"`
	Quantity  int     `json:"quantity"`
	Price     float64 `json:"price"`
}

type Mutation struct {
}

type Product struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Mark       string  `json:"mark"`
	PriceVente float64 `json:"priceVente"`
	PriceAchat float64 `json:"priceAchat"`
	Stock      float64 `json:"stock"`
	StoreID    string  `json:"storeId"`
	Store      *Store  `json:"store"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type Provider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Address   string `json:"address"`
	StoreID   string `json:"storeId"`
	Store     *Store `json:"store"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Query struct {
}

type RapportStore struct {
	ID        string   `json:"id"`
	Type      string   `json:"type"`
	Product   *Product `json:"product"`
	Quantity  float64  `json:"quantity"`
	Date      string   `json:"date"`
	StoreID   string   `json:"storeId"`
	Store     *Store   `json:"store"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type RegisterInput struct {
	Email              string  `json:"email"`
	Password           string  `json:"password"`
	Name               string  `json:"name"`
	Phone              string  `json:"phone"`
	CompanyName        string  `json:"companyName"`
	CompanyAddress     string  `json:"companyAddress"`
	CompanyPhone       string  `json:"companyPhone"`
	CompanyDescription string  `json:"companyDescription"`
	CompanyType        string  `json:"companyType"`
	CompanyEmail       *string `json:"companyEmail,omitempty"`
	CompanyLogo        *string `json:"companyLogo,omitempty"`
	CompanyRccm        *string `json:"companyRccm,omitempty"`
	CompanyIDNat       *string `json:"companyIdNat,omitempty"`
	CompanyIDCommerce  *string `json:"companyIdCommerce,omitempty"`
	StoreName          string  `json:"storeName"`
	StoreAddress       string  `json:"storeAddress"`
	StorePhone         string  `json:"storePhone"`
}

type Store struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Address   string   `json:"address"`
	Phone     string   `json:"phone"`
	CompanyID string   `json:"companyId"`
	Company   *Company `json:"company"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type UpdateClientInput struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type UpdateCompanyInput struct {
	Name        *string `json:"name,omitempty"`
	Address     *string `json:"address,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Email       *string `json:"email,omitempty"`
	Description *string `json:"description,omitempty"`
	Type        *string `json:"type,omitempty"`
	Logo        *string `json:"logo,omitempty"`
	Rccm        *string `json:"rccm,omitempty"`
	IDNat       *string `json:"idNat,omitempty"`
	IDCommerce  *string `json:"idCommerce,omitempty"`
}

type UpdateFactureInput struct {
	Products []*FactureProductInput `json:"products,omitempty"`
	ClientID *string                `json:"clientId,omitempty"`
	Quantity *int                   `json:"quantity,omitempty"`
	Price    *float64               `json:"price,omitempty"`
	Currency *string                `json:"currency,omitempty"`
	Date     *string                `json:"date,omitempty"`
}

type UpdateProductInput struct {
	Name       *string  `json:"name,omitempty"`
	Mark       *string  `json:"mark,omitempty"`
	PriceVente *float64 `json:"priceVente,omitempty"`
	PriceAchat *float64 `json:"priceAchat,omitempty"`
	Stock      *float64 `json:"stock,omitempty"`
}

type UpdateProviderInput struct {
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
}

type UpdateStoreInput struct {
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
	Phone   *string `json:"phone,omitempty"`
}

type UpdateUserInput struct {
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Email   *string `json:"email,omitempty"`
	Role    *string `json:"role,omitempty"`
	StoreID *string `json:"storeId,omitempty"`
}

type User struct {
	ID              string   `json:"id"`
	UID             string   `json:"uid"`
	Name            string   `json:"name"`
	Phone           string   `json:"phone"`
	Email           *string  `json:"email,omitempty"`
	Role            string   `json:"role"`
	IsBlocked       bool     `json:"isBlocked"`
	CompanyID       string   `json:"companyId"`
	StoreIds        []string `json:"storeIds"`
	AssignedStoreID *string  `json:"assignedStoreId,omitempty"`
	CreatedAt       string   `json:"createdAt"`
	UpdatedAt       string   `json:"updatedAt"`
}
